# Generated by Django 6.0.3 on 2026-03-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Full job description text')),
                ('requirements', models.TextField(blank=True, help_text='Specific job requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_data', models.JSONField(help_text='Complete resume data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomizedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customized_data', models.JSONField(help_text='Customized resume data optimized for the job')),
                ('customization_notes', models.TextField(blank=True, help_text='AI-generated notes about the customization')),
                ('match_score', models.FloatField(blank=True, help_text='Compatibility score (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_resumes', to='core.jobdescription')),
                ('original_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='core.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
