# Generated by Django 6.0.5 on 2026-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customizedresume_user_jobdescription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(default='template1', help_text="ID of the visual template used to render this resume, e.g. 'template1'", max_length=50),
        ),
    ]
