# Generated by Django 6.0.5 on 2026-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_url',
            field=models.URLField(blank=True, help_text='Link to the original job posting', max_length=500),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='saved', max_length=20),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(blank=True, help_text='Full job description text'),
        ),
    ]
